#!/usr/bin/env python3
"""Generate docs/spec/metrics.yaml and docs/spec/metrics_table.md FROM the code.

The metric/composite registry (one module per metric under
gaitlab/metrics/definitions/) is the single source of truth. These two files
are a generated, human-readable rendering of it — never hand-edit them.

    python scripts/gen_spec.py            # write both files
    python scripts/gen_spec.py --check    # exit 1 if either file is stale (CI)
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

import yaml  # dev-only dep

from gaitlab.metrics import spec as registry
from gaitlab.metrics.defs import METRIC_DEFS  # noqa: F401  (import side effect: registers everything)

YAML_PATH = REPO / "docs" / "spec" / "metrics.yaml"
TABLE_PATH = REPO / "docs" / "spec" / "metrics_table.md"


def build_spec_dict() -> dict:
    metrics = {}
    for key, d in METRIC_DEFS.items():
        metrics[key.value] = {
            "label": d.label,
            "unit": d.unit,
            "measurement_confidence": d.confidence,
            "evidence_level": d.evidence_level,
            "interpretation": d.interpretation,
            "views": list(d.views),
            "event_phase": d.event_phase,
            "requires_events": d.requires_events,
            "per_side": d.per_side,
            "asym_direction": d.asym_direction,
            "asymmetry_mdc": d.asymmetry_mdc,
            "reference_ids": list(d.reference_ids),
        }

    composites = {}
    for c in registry.all_composites():
        conds = []
        for cnd in c.all_of:
            rhs = f"{cnd.value}" if cnd.value is not None else cnd.band
            conds.append(f"{cnd.key.value} {cnd.op} {rhs}")
        composites[c.id] = {
            "view": c.view,
            "all_of": conds,
            "severity": c.severity,
            "interpretation": "exploratory",
            "min_confidence": c.min_confidence,
            "min_observations": c.min_observations,
            "supersedes": list(c.supersedes),
        }

    asymmetry = {
        "primary_output": "left, right, and signed difference (left - right) in the metric's native unit",
        "optional_ratio": "|L-R| / mean(|L|, |R|) * 100, omitted when the denominator is near zero",
        "flagging": "disabled unless a metric-specific validated minimum detectable change is registered",
        "metrics": {d.key.value: {"direction": d.asym_direction, "mdc": d.asymmetry_mdc}
                    for d in registry.asym_metrics()},
    }

    scoring = {
        "enabled": False,
        "reason": "No criterion-validated weighting or universal optimal bands are available for this product.",
    }

    return {"metrics": metrics, "composites": composites, "asymmetry": asymmetry, "scoring": scoring}


def render_yaml(spec: dict) -> str:
    header = (
        "# GENERATED by scripts/gen_spec.py from the code registry — DO NOT EDIT.\n"
        "# The single source of truth is gaitlab/metrics/definitions/ (one module per\n"
        "# metric) and gaitlab/metrics/definitions/composites/ (one per composite).\n"
        "# Run `python scripts/gen_spec.py` after changing a metric or composite.\n\n"
    )
    return header + yaml.safe_dump(spec, sort_keys=False, default_flow_style=None, width=100)


def render_table(spec: dict) -> str:
    lines = [
        "<!-- GENERATED by scripts/gen_spec.py — DO NOT EDIT -->",
        "# Metrics",
        "",
        "| Metric | Unit | Evidence | Measurement confidence | View | Phase | L/R | References |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for key in sorted(spec["metrics"]):
        m = spec["metrics"][key]
        lines.append(
            f"| {key} | {m['unit'] or '—'} | {m['evidence_level']} | {m['measurement_confidence']} | "
            f"{', '.join(m['views'])} | {m['event_phase']} | {'yes' if m['per_side'] else 'no'} | "
            f"{', '.join(m['reference_ids']) or '—'} |"
        )

    lines += ["", "# Composite patterns", "",
              "| Composite | View | Conditions (all of) | Minimum confidence | Minimum matching strides |",
              "|---|---|---|---|---|"]
    for name, c in spec["composites"].items():
        lines.append(
            f"| {name} | {c['view']} | {'; '.join(c['all_of'])} | "
            f"{c['min_confidence']} | {c['min_observations']} |"
        )

    return "\n".join(lines) + "\n"


def main(argv) -> int:
    spec = build_spec_dict()
    yaml_content = render_yaml(spec)
    table_content = render_table(spec)

    if "--check" in argv:
        stale = []
        if not YAML_PATH.exists() or YAML_PATH.read_text() != yaml_content:
            stale.append(YAML_PATH)
        if not TABLE_PATH.exists() or TABLE_PATH.read_text() != table_content:
            stale.append(TABLE_PATH)
        if stale:
            for p in stale:
                print(f"STALE: {p.relative_to(REPO)}")
            print("Run: python scripts/gen_spec.py")
            return 1
        print("OK: docs/spec are in sync with the code registry.")
        return 0

    YAML_PATH.write_text(yaml_content)
    TABLE_PATH.write_text(table_content)
    print(f"Wrote {YAML_PATH.relative_to(REPO)} and {TABLE_PATH.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
