#!/usr/bin/env python3
"""Generate docs/spec/metrics.yaml and docs/spec/metrics_table.md FROM the code.

The metric/composite registry (one module per metric under
gaitlab/metrics/definitions/) is the single source of truth. These two files
are a generated, human-readable rendering of it — never hand-edit them.

    python scripts/gen_spec.py            # write both files
    python scripts/gen_spec.py --check    # exit 1 if either file is stale (CI)
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

import yaml  # dev-only dep

from gaitlab.metrics import spec as registry
from gaitlab.metrics.defs import METRIC_DEFS  # noqa: F401  (import side effect: registers everything)

YAML_PATH = REPO / "docs" / "spec" / "metrics.yaml"
TABLE_PATH = REPO / "docs" / "spec" / "metrics_table.md"


def _band(b):
    lo, hi = b
    if lo is None and hi is None:
        return [None, None]
    return [lo, hi]


def _band_str(b):
    lo, hi = b
    if lo is None and hi is None:
        return "—"
    if lo is None:
        return f"≤ {hi}"
    if hi is None:
        return f"≥ {lo}"
    return f"{lo}–{hi}"


def build_spec_dict() -> dict:
    metrics = {}
    for key, d in METRIC_DEFS.items():
        metrics[key.value] = {
            "label": d.label,
            "unit": d.unit,
            "good": _band(d.good),
            "warn": _band(d.warn),
            "confidence": d.confidence,
            "views": list(d.views),
            "scored": d.scored,
            "per_side": d.per_side,
            "asym_direction": d.asym_direction,
        }

    composites = {}
    for c in registry.all_composites():
        conds = []
        for cnd in c.all_of:
            rhs = f"{cnd.value}" if cnd.value is not None else cnd.band
            conds.append(f"{cnd.key.value} {cnd.op} {rhs}")
        composites[c.id] = {
            "view": c.view,
            "all_of": conds,
            "severity": c.severity,
            "supersedes": list(c.supersedes),
        }

    from gaitlab.metrics.keys import MetricKey
    asym_t = METRIC_DEFS[MetricKey.ASYMMETRY]
    asymmetry = {
        "formula": "AI = |L - R| / mean(|L|, |R|) * 100",
        "bands": {"good": _band(asym_t.good), "warn": _band(asym_t.warn)},
        "suppression": "If both sides are individually within their metric's good band, the flag is suppressed.",
        "metrics": {d.key.value: d.asym_direction for d in registry.asym_metrics()},
    }

    scoring = {
        "per_metric": {"good": 100, "warn_edge": 45, "deep_bad": 17.5, "nan": 50, "frac_clamp": 1.5, "slope": 55},
        "overall": {
            "base": "mean of scored-metric scores for the view",
            "penalty": "clamp(mean(flagged asymmetry diffs) * 0.8, 0, 22)",
            "formula": "clamp(base - penalty, 0, 100)",
        },
        "grades": {"A": 85, "B": 72, "C": 58, "D": 42},
        "scored_keys_side": sorted(k.value for k in registry.scored_keys("side")),
        "scored_keys_rear": sorted(k.value for k in registry.scored_keys("rear")),
    }

    return {"metrics": metrics, "composites": composites, "asymmetry": asymmetry, "scoring": scoring}


def render_yaml(spec: dict) -> str:
    header = (
        "# GENERATED by scripts/gen_spec.py from the code registry — DO NOT EDIT.\n"
        "# The single source of truth is gaitlab/metrics/definitions/ (one module per\n"
        "# metric) and gaitlab/metrics/definitions/composites/ (one per composite).\n"
        "# Run `python scripts/gen_spec.py` after changing a metric or composite.\n\n"
    )
    return header + yaml.safe_dump(spec, sort_keys=False, default_flow_style=None, width=100)


def render_table(spec: dict) -> str:
    lines = [
        "<!-- GENERATED by scripts/gen_spec.py — DO NOT EDIT -->",
        "# Metrics",
        "",
        "| Metric | Unit | Good | Warn | Confidence | Views | Scored |",
        "|---|---|---|---|---|---|---|",
    ]
    for key in sorted(spec["metrics"]):
        m = spec["metrics"][key]
        lines.append(
            f"| {key} | {m['unit'] or '—'} | {_band_str(m['good'])} | {_band_str(m['warn'])} | "
            f"{m['confidence']} | {', '.join(m['views'])} | {'yes' if m['scored'] else 'no'} |"
        )

    lines += ["", "# Composite patterns", "",
              "| Composite | View | Conditions (all of) | Severity |", "|---|---|---|---|"]
    for name, c in spec["composites"].items():
        lines.append(f"| {name} | {c['view']} | {'; '.join(c['all_of'])} | {c['severity']} |")

    return "\n".join(lines) + "\n"


def main(argv) -> int:
    spec = build_spec_dict()
    yaml_content = render_yaml(spec)
    table_content = render_table(spec)

    if "--check" in argv:
        stale = []
        if not YAML_PATH.exists() or YAML_PATH.read_text() != yaml_content:
            stale.append(YAML_PATH)
        if not TABLE_PATH.exists() or TABLE_PATH.read_text() != table_content:
            stale.append(TABLE_PATH)
        if stale:
            for p in stale:
                print(f"STALE: {p.relative_to(REPO)}")
            print("Run: python scripts/gen_spec.py")
            return 1
        print("OK: docs/spec are in sync with the code registry.")
        return 0

    YAML_PATH.write_text(yaml_content)
    TABLE_PATH.write_text(table_content)
    print(f"Wrote {YAML_PATH.relative_to(REPO)} and {TABLE_PATH.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
