#!/usr/bin/env python3
"""Render human-readable spec tables from the canonical docs/spec/metrics.yaml.

    python scripts/gen_spec_tables.py            # write docs/spec/metrics_table.md
    python scripts/gen_spec_tables.py --check    # exit 1 if the file is stale (CI)

The YAML is the single source of truth; this produces the readable rendering and
lets CI detect drift between the two.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
SPEC_PATH = REPO / "docs" / "spec" / "metrics.yaml"
OUT_PATH = REPO / "docs" / "spec" / "metrics_table.md"


def _band(b) -> str:
    lo, hi = b
    if lo is None and hi is None:
        return "—"
    if lo is None:
        return f"≤ {hi}"
    if hi is None:
        return f"≥ {lo}"
    return f"{lo}–{hi}"


def render(spec: dict) -> str:
    metrics = spec["metrics"]
    lines = [
        "<!-- GENERATED by scripts/gen_spec_tables.py from docs/spec/metrics.yaml — DO NOT EDIT -->",
        "# Metrics (generated from metrics.yaml)",
        "",
        "| Metric | Tier | Unit | Good | Warn | Confidence | Views | Scored |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for key in sorted(metrics):
        m = metrics[key]
        lines.append(
            f"| {key} | {m.get('tier','')} | {m['unit'] or '—'} | {_band(m['good'])} | "
            f"{_band(m['warn'])} | {m['confidence']} | {', '.join(m['views'])} | "
            f"{'yes' if m['scored'] else 'no'} |"
        )

    lines += ["", "# Composite patterns", "",
              "| Composite | View | Status | Conditions (all of) | Severity |",
              "|---|---|---|---|---|"]
    for name, c in spec.get("composites", {}).items():
        conds = "; ".join(c["all_of"])
        lines.append(f"| {name} | {c['view']} | {c['status']} | {conds} | {c['severity']} |")

    lines += ["", "# Requirements", "",
              "| ID | Status | Description |", "|---|---|---|"]
    for rid in sorted(spec.get("requirements", {})):
        r = spec["requirements"][rid]
        lines.append(f"| {rid} | {r['status']} | {r['description']} |")

    return "\n".join(lines) + "\n"


def main(argv) -> int:
    spec = yaml.safe_load(SPEC_PATH.read_text())
    content = render(spec)
    if "--check" in argv:
        current = OUT_PATH.read_text() if OUT_PATH.exists() else ""
        if current != content:
            print(f"STALE: {OUT_PATH.relative_to(REPO)} is out of date with metrics.yaml.")
            print("Run: python scripts/gen_spec_tables.py")
            return 1
        print(f"OK: {OUT_PATH.relative_to(REPO)} is in sync with metrics.yaml.")
        return 0
    OUT_PATH.write_text(content)
    print(f"Wrote {OUT_PATH.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
